### PR TITLE
[#148] Upgrade to operator sdk 0.17.2

### LINKED ISSUE #148: Upgrade operator SDK to v0.17.2
This upgrade will bring in compatibility with OpenShift 4.4

### PR DESCRIPTION
**Pull request by yersan**
This fixes #148

### CODE REVIEW

**Comment by jmesnil** [comment]
The CI highlighted something fishy with the operator-sdk 0.17.2 version.
In the PR (https://github.com/wildfly/wildfly-operator/tree/2c1582be6d7145ceb736a444d4b58dd639caf3fb/vendor/github.com/operator-framework/operator-sdk/internal/), the vendorized module does not have an internal/scaffold while it actually present in the tag at https://github.com/operator-framework/operator-sdk/tree/v0.17.2/internal/scaffold

**Comment by jmesnil** [comment]
@yersan sorry, that's my mistake: in .gitignore, I've added `operator-sdk` to ignore the binary file that can be installed at the root but this was wrong: it also ignore any directory named `operator-sdk`.

Could you please fix the `.gitignore` in your PR with:
```
./operator-sdk
./openapi-gen
```

With that change, you will be able to add the missing files in the operator-sdk module.

**Comment by jmesnil** [comment]
the 2 CI tests on ci/prow pass now. I think we can now get rid of Travis CI and relues only on ci/prow for CI testing. wdyt?

I'm fine with merging the PR as it is
@yersan Are you fine with this PR or is there anything else you want to do with it?

**Comment by yersan** [comment]
Hello @jmesnil , I've just squashed the commits and removed the draft PR converting it into a normal one. The test should pass again and I don't have any additional commit to add to this one. I'm fine getting rid of travis now.

**Comment by jmesnil** [comment]
@yersan thanks!

**Pull request merged**
